using System.Collections;
using System.Collections.Generic;
using UnityEngine;


/// Controls the traversal, health state, and animation lifecycle of enemy entities.
/// Manages waypoint navigation and interfaces with the global economy and base systems upon death or success.

public class EnemyMovement : MonoBehaviour
{

    // STATE & DATA
    private EnemyData myData; // Reference to the ScriptableObject defining baseline stats.
    [HideInInspector] public float currentHealth; // Current hit points of the entity.
    [HideInInspector] public float currentSpeed; // Active movement speed, separated from base stats to allow dynamic modification.

    public bool isDead = false; // Prevents redundant death sequence execution and targeting.


    // NAVIGATION
    private List<Vector3> waypoints; // The sequential list of spatial coordinates defining the path.
    private int currentTargetIndex = 0; // The index of the immediate waypoint objective.


    // COMPONENTS
    private Animator anim; // Cached reference to the child animator component.

    
    /// Bootstraps the entity with path data and baseline statistics, and synchronizes the animation speed.
    
    /// The list of Vector3 waypoints generated by the map.
    /// The scriptable object containing the specific enemy type data.
    public void Initialize(List<Vector3> pathList, EnemyData data)
    {
        waypoints = pathList;
        currentTargetIndex = 0;

        myData = data;        
        currentSpeed = myData.moveSpeed;

        anim = GetComponentInChildren<Animator>();

        if (anim != null)
        {
            // Calculate a multiplier to ensure physical movement speed matches the visual animation cycle.
            float speedMultiplier = currentSpeed / myData.baseAnimationWalkSpeed;
            anim.speed = speedMultiplier;
            anim.SetBool("IsWalking", true);
        }

        // Snap the entity to the starting coordinate.
        if (waypoints != null && waypoints.Count > 0)
        {
            transform.position = waypoints[0];
        }
    }

    /// Processes positional translation and rotation towards the active waypoint each frame.
    void Update()
    {
        // Suspend all logic if the entity is dead, lacks path data, or has completed the route.
        if (isDead || waypoints == null || currentTargetIndex >= waypoints.Count || myData == null) return;

        Vector3 targetPosition = waypoints[currentTargetIndex];

        // Execute linear translation towards the current objective.
        transform.position = Vector3.MoveTowards(transform.position, targetPosition, currentSpeed * Time.deltaTime);

        // Calculate and apply smooth rotational orientation towards the movement vector.
        Vector3 moveDirection = (targetPosition - transform.position).normalized;
        if (moveDirection != Vector3.zero)
        {
            Quaternion targetRotation = Quaternion.LookRotation(moveDirection);
            transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, myData.turnSpeed * Time.deltaTime);
        }

        // Evaluate proximity to the active waypoint to determine if the next index should be targeted.
        if (Vector3.Distance(transform.position, targetPosition) < 0.05f)
        {
            currentTargetIndex++;
            if (currentTargetIndex >= waypoints.Count)
            {
                ReachBase();
            }
        }
    }


    public float GetPathProgress()
    {
        if (waypoints == null || waypoints.Count == 0) return 0f;

        // Apply a heavy weight to the waypoint index to ensure progression.
        float progressScore = currentTargetIndex * 1000f;

        // Subtract the remaining physical distance to the active waypoint for sorting.
        progressScore -= Vector3.Distance(transform.position, waypoints[currentTargetIndex]);

        return progressScore;
    }


    /// Reduces the entity's health by the specified damage value and evaluates mortality.
    public void TakeDamage(float damageAmount)
    {
        // Abort damage processing if the death sequence has already been initiated.
        if (isDead) return;

        currentHealth -= damageAmount;

        if (currentHealth <= 0)
        {
            Die();
        }
    }

    /// Disable actor, death animation, and gives player fur.
    private void Die()
    {
        isDead = true;
        currentSpeed = 0f;

        Collider myCollider = GetComponent<Collider>();
        if (myCollider != null)
        {
            myCollider.enabled = false;
        }

        if (BaseManager.Instance != null)
        {
            BaseManager.Instance.AddFur(myData.furReward);
        }

        if (AudioManager.Instance != null)
        {
            AudioManager.Instance.PlayDeathSound();
        }

        if (anim != null)
        {
            anim.speed = 1f;
            anim.SetBool("IsWalking", false);

            // This forces the Animator to instantly snap to the "Die" state, 
            // starting exactly at frame 0, ignoring all transitions and delays.
            // Make sure your state in the Animator window is actually named "Die"!
            anim.Play("Die", 0, 0f);

            StartCoroutine(WaitForDeathAnimation());
        }
        else
        {
            Destroy(gameObject);
        }
    }

    
    /// A coroutine that dynamically reads the length of the active death animation.
    /// Incorporates State Hash checking to prevent premature deletion during spawn-kills.
    
    private IEnumerator WaitForDeathAnimation()
    {
        // 1. Yield exactly one frame to allow the anim.Play() command to apply to the mesh
        yield return null;

        float animationLength = anim.GetCurrentAnimatorStateInfo(0).length;
        yield return new WaitForSeconds(animationLength);

        Destroy(gameObject);
    }

    
    /// Handles the event where the entity successfully navigates the entire path.
    
    private void ReachBase()
    {
        // Failsafe to prevent a destroyed entity from interacting with the base.
        if (isDead) return;

        Debug.Log($"{myData.enemyName} reached the base. Dealing {myData.baseDamage} damage.");

        if (BaseManager.Instance != null)
        {
            BaseManager.Instance.TakeDamage(myData.baseDamage);
        }

        gameObject.SetActive(false);
        Destroy(gameObject);
    }
}